[package]
edition = "2021"
name = "grpc-server"
version = "0.1.0"

[dependencies]
env_logger = "0.11.3"
log = "0.4"
prost = "0.12"
tokio = {version = "1.0", features = ["macros", "rt-multi-thread"]}
tonic = "0.11"
tonic-reflection = "0.11"

[build-dependencies]
tonic-build = "0.11"
