services:
  grpc:
    image: grpc-server-test:latest
    ports:
      - "8080:80"
    environment:
      - RUST_LOG=debug
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:80", "-connect-timeout=1s", "-rpc-timeout=1s"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
